name:                cursed-pfp-maker
version:             0.1.0.0
github:              "skiros8732/cursed-pfp-maker"
license:             BSD3
author:              "skiros"
maintainer:          "skiros@skiros.me"
copyright:           "2021 skiros"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/skiros8732/cursed-pfp-maker#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cursed-pfp-maker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cursed-pfp-maker

tests:
  cursed-pfp-maker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cursed-pfp-maker
